services:
  - type: web
    name: vybesync-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GENIUS_TOKEN
        sync: false
